[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=unexpected
stopsignal=QUIT
stopwaitsecs=3600
stopasgroup=true
killasgroup=true
stdout_events_enabled=true
stderr_events_enabled=true
